{% set name = "ligotimegps" %}
{% set version = "1.2.3" %}
{% set sha256 = "79ee18df7f6806d522f68d278b0ac426094626a479af58c178f32d2b319919ba" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  noarch: python
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - setuptools
    - pip
  run:
    - python
    - six

test:
  requires:
    - pytest
  commands:
    - pytest --pyargs {{ name }}

about:
  home: https://pypi.org/project/{{ name }}/
  license: GPLv3
  license_file: LICENSE
  license_family: GPL
  summary: A pure-python version of lal.LIGOTimeGPS
  description: |
    This module provides a pure-python version of the `LIGOTimeGPS` class,
    used to represent GPS times (number of seconds elapsed since GPS epoch)
    with nanoseconds precision.

    This module is primarily for use as a drop-in replacement for the
    'official' `LIGOTimeGPS` class (provided by `lal`) for use on those
    environments where LAL is not available (e.g. Windows), or when
    building LAL is unnecessary for the application (e.g. testing).

    The code provided here is much slower than the C-implementation
    provided by LAL, so if you really care about performance,
    don't use this module.

extra:
  recipe-maintainers:
    - duncanmmacleod
