{% set name = "ligotimegps" %}
{% set version = "2.1.0" %}

{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/l/ligotimegps/ligotimegps-{{ version }}.tar.gz
  sha256: d948ffc4d58472b303478a983ec56d2e6a7f35e54cbb351ca6f1292e68398cb2

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools >=61.0
    - setuptools-scm >=6.2
  run:
    - python >={{ python_min }}

test:
  requires:
    - pip
    - pytest >=8.4.1
    - python {{ python_min }}
  commands:
    # check requirements
    - python -m pip check
    - python -m pip show ligotimegps
    # run tests
    - python -m pytest --pyargs -ra -v ligotimegps.tests

about:
  home: https://pypi.org/project/ligotimegps/
  dev_url: https://gitlab.com/gwpy/ligotimegps.git
  doc_url: https://ligotimegps.readthedocs.io/
  license: GPL-3.0-or-later
  license_file: LICENSE
  summary: A pure-python version of lal.LIGOTimeGPS
  description: |
    This module provides a pure-python version of the `LIGOTimeGPS` class,
    used to represent GPS times (number of seconds elapsed since GPS epoch)
    with nanoseconds precision.

    This module is primarily for use as a drop-in replacement for the
    'official' `LIGOTimeGPS` class (provided by `lal`) for use on those
    environments where LAL is not available (e.g. Windows), or when
    building LAL is unnecessary for the application (e.g. testing).

    The code provided here is much slower than the C-implementation
    provided by LAL, so if you really care about performance,
    don't use this module.

extra:
  recipe-maintainers:
    - duncanmmacleod
