travis:
  secure:
    BINSTAR_TOKEN: ZPzrgNJhwMPO8W2EPSQFJwaUpkv0PMdEblA6zrkg1/rLjdGwMPmpKpAuyCBbkCPyxC4dm3LFKw3qSQhbWgCFIx2fQ0mWnDQY97EMFJ0+jeh5NP3m/luQgB9NX1jEk+Bgfp+ng8f2miFheuHXwG9yV51NHTHRS5Ta82y3GmXy2pHXJDdYpl6mrLmjIoYSzQ5BBcJQrkVQks+5WojwpPstei/EFWsljHHBgztggjsHkEiqdnH7AEUlM7/ZBGYvc0Me+2DLfcFUUoiSyZ8GT3g/oD2qHuK3a+/sBIqPHEaMTRiOe/WJobgS1WWrc7WbZdVEck+XHmp7IhG/eb0lkmEUjV+j5+KVzF2IaZPFt+dOoKjIElHRlgX4HZ2zWfXwxowsENpxB64vGLuvwUxYENdbHFEc6EFTALlVUJ7v6TJwygjvS1HhYeMvu1fxXGHdfsewmM8DGvikUweiwNiMtjE+QOYAaf9AArZh2yhIc3/8dG+ANuVlQwocvrVKeQ4PurTj8ENWpiBAonNTri8DQq8kouT7zqNfo4i22J80X7g/vp+6p+iR4K5uzHwbn4iDNtPDocadnGWBBF16A0eaiJLD6Ohl1RFI90ds7JAvMDjKhnhJDlGm3IFX8b0do8G1wHQY4Hiu++WQQp9SggkZ+fkQ2lb5Mh8mM3I2jAXMrh8gIB0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
