travis:
  secure:
    BINSTAR_TOKEN: J6jXqb1IYpTL58r6GvSPyZqSZ+rW3BU/MzEJbheEy186lyLVMQJkAZhQJQfCGrOg1b7rt5KdI6QjUZGO2icfrAmS2CKMDpfTXDcIeuR2tR2Xig/YSAn9wbyL1nIawnwpCAp0SF7+47L955dQuvXfhFEeMuiyC1n7SpAeI/gHBgj79lzcj30RIpJ+Z488Dtm0xm+OCRojHUFjSNsO7sjieO39tlCcp9IHksjaBnUOIznbMgX1za9W2rvjd48iRR6kfpH6XzhQExTIrBUsy3OOeMu417D1JrZEYkcnsoyAh79WRFwNzYh/D0I5r0O/U4d4cbST+A5nqQmRJDbSGZM7dQdvEvFv3vvo814pOWd/BgxDgjhmY3eQXQHXLDez+4+oS+WSgKZHRvcQQDLlKpPjvYeyx1DLeL3OH/8w0FDyWFkhkZEYt2z64qDul2d71sQbPRmGyJ050+nT0QemiXtb0/2sQ1bN/y1L0xVkH4YAU11+rXe6L7e+8a0l0lLqGts2xfJ1ZkhzyXO9fZpl3FHXOKndpVADlEdChn7fYnPwhSgydBvD8ZvODvt/MXVEMCj9zksCBb/qdJ/v5KMfOh59Hnz41duRbFFVHXYANQzI0sEzueHUYcSB9XhNWJHWhUAZV4Fro3eJHq9Cj2SmMA7gvV1q20pulYQB+/34Qd41C1E=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
